export const LOADING = "LOADING"
export const STOP_LOADING = "STOP_LOADING"
export const ADD_REGISTER_SUCESS = "ADD_REGISTER_SUCESS";
export const ADD_REGISTER_FAIL = "ADD_REGISTER_FAIL";
export const FETCH_MEASUREMENTS_SUCCESS = "FETCH_MEASUREMENTS_SUCCESS"
export const FETCH_MEASUREMENTS_FAIL = "FETCH_MEASUREMENTS_FAIL"
export const RESTART_FLAGS = "RESTART_FLAGS"